import { ICredentials } from "@serverless-devs/component-interface";
import Sls20201230, {
  InitSlsRequest,
} from "@serverless-cd/srm-aliyun-sls20201230";
import { Config } from "@alicloud/openapi-client";
import GLogger from "../common/logger";

export default class Sls {
  static generateProjectName = (region: string, accountID: string): string =>
    `aliyun-serverless-${accountID}-${region}`;
  static generateLogstoreName = (): string => {
    return "default-logs";
  };

  readonly client: Sls20201230;
  private accountID: string;

  constructor(
    private region: string,
    credentials: ICredentials,
  ) {
    const config = new Config({
      accessKeyId: credentials.AccessKeyID,
      accessKeySecret: credentials.AccessKeySecret,
      securityToken: credentials.SecurityToken,
      endpoint: `${region}.log.aliyuncs.com`,
      userAgent: "serverless-devs",
      regionId: region,
      readTimeout: 60000,
      connectTimeout: 5000,
    });
    this.client = new Sls20201230(config);
    this.accountID = credentials.AccountID;
  }

  async deploy(): Promise<{ project: string; logstore: string }> {
    const project = Sls.generateProjectName(this.region, this.accountID);
    const logstore = Sls.generateLogstoreName();

    const request = new InitSlsRequest({
      project,
      logstore,
      description: "Generated by Aliyun fc3.x component",
      accountID: this.accountID,
      region: this.region,
    });

    GLogger.getLogger().debug(`init sls: ${JSON.stringify(request)}`);

    GLogger.getLogger().spin(
      "creating",
      "sls",
      `region: ${this.region}; project: ${project}; logstore: ${logstore}`,
    );
    await this.client.initSls(request);
    GLogger.getLogger().spin(
      "created",
      "sls",
      `region: ${this.region}; project: ${project}; logstore: ${logstore}`,
    );
    return { project, logstore };
  }
}
